name: 'Marlin Firmware'
title: 'Marlin Firmware'
logo: '/assets/images/logo/marlin/text-night.png'
description: 'Printing the planet, one layer at a time.'

baseurl: ''
url: 'https://marlinfw.org'
js: '/assets/javascript/'
pull_img: '/assets/images/docs/development/pull_images/'
destination: ./_site

#theme: jekyll-theme-documentation
#theme: jekyll-theme-minimal
theme: just-the-docs
#nav_enabled: true

color_scheme: dark

twitter:
  username: MarlinFirmware

social:
  name: Marlin Firmware
  links:
    - https://fosstodon.org/@marlinfirmware
    - https://x.com/marlinfirmware
    - https://bsky.app/profile/marlinfw.org
    - https://www.facebook.com/groups/1049718498464482/
    - http://forums.reprap.org/list.php?415
    - https://discord.com/servers/marlin-firmware-461605380783472640

#github:
#  repository_name: 'MarlinFirmware/MarlinDocumentation'
#  repository_url:

repository:
  main: 'https://github.com/MarlinFirmware/Marlin'
  doc: 'https://github.com/MarlinFirmware/MarlinDocumentation'
  config: 'https://github.com/MarlinFirmware/Configurations'

# Google Analytics Tracking (optional)
ga_tracking: UA-76230130-10
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

analytics:
  id: 'UA-76230130-1'
  domain: 'marlinfw.org'

markdown: kramdown
highlighter: rouge
timezone: 'America/Chicago'

kramdown:
  input: GFM
  syntax_highlighter: rouge

jekyll_tidy:
  compress_html: true
  # exclude: ["index.html"]
  # ignore_env: development

sass:
    style: compressed

collections:
  basics:
    output: true
    permalink: /docs/:collection/:path:output_ext

exclude:
  - _config.yml
  - Gemfile
  - LICENSE
  - public
  - script
  - vendor

plugins:
  #- jekyll-toc
  - jekyll-bootstrap-sass
  - jekyll-tidy
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - # All types
    scope:
      path: '' # all files
    values:
      layout: default
      author: MarlinFirmware
      category: [ default ]
      show:
        navbar: true
        footer: true
        breadcrumbs: false

  - # Basics collection
    scope:
      type: basics
    values:
      layout: page
      category: [ Basics ]

# SEO Stuff
author: Marlin Firmware
summary: Documentation for the Marlin Firmware project.
lang: en
locale: en_US

# RSS feeds
feed:
  posts_limit: 20

# Obtrusive links not properly styled
#aux_links:
#  Just the Docs on GitHub:
#    - https://github.com/just-the-docs/just-the-docs

# Just the Docs theme configuration
aux_links:
  🤓 GitHub: https://github.com/MarlinFirmware/Marlin
  ❤️ Donate: /docs/contribute.html
